### PR TITLE
Missing code for meteo sensors in arduino library.

### PR DESCRIPTION
**Pull request by lesny8**

### CODE REVIEW

**Review by przemyslawzygmunt — CHANGES_REQUESTED** [review]
The value -275 is only incorrect for thermometers because it goes beyond the range of possible temperatures.

**Comment by lesny8** [comment]
Ok. I changed the values to -1

**Review by przemyslawzygmunt — CHANGES_REQUESTED** [review]
_cb_arduino_get_distance, _cb_arduino_get_pressure, _cb_arduino_get_weight etc... can be replaced by one typedef.

typedef double (*_cb_arduino_get_double)(int channelNumber, double current_value);

**Comment by lesny8** [comment]
Good point :)

**Pull request merged**
